#!/usr/bin/env python
# This program logs data from speclab instruments. See the README file for usage
# notes, or use speclag -h to display the help information.
#
# Timothy Crone (tjcrone@gmail.com)

# imports
import sys, os, serial, time, argparse, signal
from socket import gethostname 

# get hostname
hostname=gethostname()

# default device ports
if hostname=='europa':
  mb_port = '/dev/tty.usbserial-FT9JW0SS'
  ir_port = '/dev/tty.usbserial-FT9JW7R8'

# signal handler function
running=True
def signal_handler(signal, frame):
  running=False
  clean_quit()
signal.signal(signal.SIGINT, signal_handler)

# define required globals as empty
f = []
mb = []
ir = []

# clean up and quit function
def clean_quit():
  if not args.veryquiet:
    sys.stderr.write("\b\bCleaning up ... ")
  if f: f.close()
  if mb: mb.ser.close()
  if ir: ir.ser.close()
  if not args.veryquiet:
    sys.stderr.write("done.\n")
  raise SystemExit

# default output file function
def default_output():
  output = time.strftime('%Y_%m_%d_%H%M%S.log', time.gmtime())
  return output

# parse arguments
parser = argparse.ArgumentParser(description='Data logger for SpecLab instruments')
parser.add_argument('-v', '--version', action='version', version='%(prog)s version 0.3dev')
parser.add_argument("-d", dest="device", nargs='+', metavar=('name', 'port'),
  default=[], action='append', help="device [and port] to log (options: mb, ir)")
parser.add_argument("-e", dest="emissivity", metavar="emissivity", type=float, default=1.0,
  help="change emissivity (default: 1.0)")
parser.add_argument("-i", dest="interval", metavar="seconds", type=int, default=5,
  help="interval between log entries (default: 5)")
parser.add_argument("-n", dest="total_samples", metavar="samples", type=int, default=[],
  help="number of samples to log (default: inf)")
parser.add_argument("-t", dest="total_seconds", metavar="seconds", type=int, default=[],
  help="total time to log (default: inf)")
parser.add_argument("-o", dest="output", metavar="filename", type=str, nargs='?',
  default=argparse.SUPPRESS, help="output file name (default: based on start time)")
parser.add_argument("-q", dest="quiet", action='store_true',
  default=False, help="suppress output to stdout")
parser.add_argument("-qq", dest="veryquiet", action='store_true',
  default=False, help="suppress all screen output")
args = parser.parse_args()

#set quiet if veryquiet
if args.veryquiet:
  args.quiet = True

# define output file as necessary
try:
  if args.output is None:
    args.output = default_output()
except:
  args.output = False

# default devices
if not args.device:
  args.device = [['mb'], ['ir']]

# default ports
for dev in args.device:
  if len(dev) == 1:
    if dev[0] == 'mb':
      dev.append(mb_port)
    elif dev[0] == 'ir':
      dev.append(ir_port)
    else:
      parser.error("argument -d: the first device argument must be either 'mb' or 'ir'")

# error check device arguments
for dev in args.device:
  if len(dev)>2:
    parser.error("argument -d: device option takes a maximum of two arguments")
  if not os.path.exists(dev[1]):
    parser.error("argument -d: device path '%s' does not exist" % dev[1])

# error check output file
if args.output:
  if os.path.isdir(args.output):
    parser.error("argument -o: output file argument '%s' is a directory" % args.output)
  if os.path.exists(args.output):
    parser.error("argument -o: output file '%s' already exists" % args.output)
  try:
    f = open(args.output, 'a')
    f.close()
    os.remove(args.output)
  except:
    raise

# simple device object for namespace convenience
class Device(object):
  pass

# create requested devices
for dev in args.device:
  if dev[0] == 'mb':
    # create  mass balance serial object
    mb = Device()
    mb.name = 'mass balance'
    mb.ser = serial.Serial(baudrate=9600, parity=serial.PARITY_NONE,
      stopbits=serial.STOPBITS_TWO, bytesize=serial.SEVENBITS, timeout=0.25)
    mb.ser.port = dev[1]
  elif dev[0] == 'ir':
    # create  ir pyrometer serial object
    ir = Device()
    ir.name = 'ir pyrometer'
    ir.ser = serial.Serial(baudrate=9600, parity=serial.PARITY_NONE,
      stopbits=serial.STOPBITS_ONE, bytesize=serial.EIGHTBITS, timeout=0.1)
    ir.ser.port = dev[1]

# connector routine
def connect(device):
  if not args.veryquiet:
    sys.stderr.write("Connecting to %s ... " % device.name)
  num_tries = 10
  n = 0
  while True:
    try:
      device.ser.open()
    except:
      if sys.exc_info()[1].errno == 16: # loop for num_tries on resource busy error
        n = n+1
        if n == num_tries:
          if not args.veryquiet:
            sys.stderr.write("failed.\nError opening %s port '%s' after %i tries: Resource busy.\n" %
              (device.name, device.ser.port, num_tries))
          raise SystemExit
        else:
          time.sleep(1)
          continue
      else:
        raise # raise the SerialException on any other error
    if not args.veryquiet:
      sys.stderr.write("done.\n")
    break

# connect to defined devices
if mb: connect(mb)
if ir: connect(ir)

# set ir emissivity
if ir:
  ir.ser.write('EMI %f\n' % args.emissivity)

# get ir emissivity
# this can be cut once we trust the emissivity write
if ir:
  ir.ser.flushInput()
  ir.ser.write('EMI ?\n')
  ir_data = ir.ser.readline().strip()
  # format ir emissivity
  if len(ir_data)>0:
    if 'ERROR' in ir_data:
      ir_emi = "ND"
    else:
      ir_emi = ir_data.split(' ')[0]
      if not check_float(ir_emi):
        ir_emi = "ND"
  else:
    ir_emi = 'ND'
else:
  ir_emi = 'ND'

print ir_emi

clean_quit()

# function to check if device value is a valid float
def check_float(value):
  try:
    float(value)
    return True
  except ValueError:
    return False

# initialize some counters
total_seconds = 0 # total number of seconds elapsed
total_samples = 0 # total number of samples logged
interval_seconds = 0 # number of seconds elapsed per interval

# open output file
if args.output:
  f = open(args.output, 'w')

# write logging started message to stderr
if args.output:
  if not args.veryquiet:
    sys.stderr.write("Logging data to %s every %i s.\n" % (args.output, args.interval))
if not args.veryquiet:
  sys.stderr.write("Press Ctrl-C to quit logging.\n\n")
 
# write header
if not args.quiet:
  sys.stdout.write('Emissivity: %f\n' % (args.emissvity))
  sys.stdout.flush()
if args.output:
  f.write('Emissivity: %f\n' % (args.emissvity))
  f.flush()

# loop to log data
while running:
  # quit if requested number of samples have been collected
  if args.total_samples:
    if total_samples == args.total_samples:
      clean_quit()

  # quit if requested logging time has elapsed 
  if args.total_seconds:
    if total_seconds == args.total_seconds:
      clean_quit()

  # sleep for one second
  time.sleep(1 - time.time() % 1)

  # clear mb input buffer (needs to be done often)
  if mb: mb.ser.flushInput()

  # increment counters
  total_seconds = total_seconds+1
  interval_seconds = interval_seconds+1

  # log sample according to the logging inverval
  if interval_seconds == args.interval or total_seconds == 1:
    total_samples = total_samples+1
    interval_seconds = 0

    # get sample time
    sample_time = time.strftime('%Y,%m,%d,%H,%M,%S', time.gmtime())

    # get mb data
    if mb:
      mb.ser.flushInput()
      mb_data = mb.ser.readline().strip()
      mb_data = mb.ser.readline().strip() # get two lines in case the first one is truncated
      # format mb value
      if len(mb_data)>0:
        mb_value = mb_data.split(' ')[0]
        # check if mb_value is a float
        if not check_float(mb_value):
          mb_value = "ND"
      else:
        mb_value = 'ND'
    else:
      mb_value = 'ND'

    # get ir temperature
    if ir:
      ir.ser.flushInput()
      ir.ser.write('TEM ?\n')
      ir_data = ir.ser.readline().strip()
      # format ir temperature
      if len(ir_data)>0:
        if 'ERROR' in ir_data:
          ir_tmp = "ND"
        else:
          ir_tmp = ir_data.split(' ')[0]
          if not check_float(ir_tmp):
            ir_tmp = "ND"
      else:
        ir_tmp = 'ND'
    else:
      ir_tmp = 'ND'

    # get ir ambient
    if ir:
      ir.ser.flushInput()
      ir.ser.write('AMB ?\n')
      ir_data = ir.ser.readline().strip()
      # format ir ambient
      if len(ir_data)>0:
        if 'ERROR' in ir_data:
          ir_amb = "ND"
        else:
          ir_amb = ir_data.split()[2]
          if not check_float(ir_amb):
            ir_amb = "ND"
      else:
        ir_amb = 'ND'
    else:
      ir_amb = 'ND'

    # write results to screen
    if not args.quiet:
      sys.stdout.write('%s,%s,%s,%s\n' % (sample_time, mb_value, ir_tmp, ir_amb))
      sys.stdout.flush()

    # write results to file
    if args.output:
      f.write('%s,%s,%s,%s\n' % (sample_time, mb_value, ir_tmp, ir_amb))
      f.flush()
